# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1bbfa19fb34ac243c65f944fdd64a13e339bb4cc2c7b6aa92ff8c4766aacd14ea5a73a45f8ed16d93807593eb87db2fc703fbe3a7b8a71a86600a4d8072c17

test:
  secret_key_base: 56e5b268f9da79c89451dd88913d3594d3c8fd849c2ae3199b4db5ad34aa88c0c437b71b1bdabdf72cdc0facfa810337a1448ad1fa9fe6b5c436a0ae16dbc5df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
