:store_name: The Dinner Store
:tagline: Where it's at!
:promo_text: The dinner store is where it is at for all your dinner related supplies!  We have the very best in tables
             chairs, plates and silverware!
:copyright: "© Copyright no one at all. Go to town."
